name = "SimpleEvolve"
uuid = "6d5e804b-4f14-450a-9571-280c5529278f"
authors = ["Nick and Arnab"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
LinearAlgebra = "1.11.0"
Plots = "1.40.11"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
